version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ${PWD}/conf.d:/etc/nginx/conf.d
      - ${PWD}/www:/usr/share/nginx/html
      - ${PWD}/report:/srv/report
      - ${PWD}/logs:/var/log/nginx
    # networks:
    #   test:
    #     ipv4_address: 172.20.0.3

  goaccess:
    image: allinurl/goaccess:1.6.5
    # restart: always
    # networks:
    #   test:
    #     ipv4_address: 172.20.0.4
    expose:
      - 7890
    volumes:
      # - ${PWD}:/srv/logs:ro
      - ${PWD}/logs:/var/log/nginx:ro
      # - ${PWD}:/srv/report
      - ${PWD}/goaccess:/srv/data
      - ${PWD}/report:/srv/report
    command: ["--no-global-config", "--config-file=/srv/data/goaccess.conf"]

# volumes:
#   goaccess_report:
#     name: goaccess_report

# networks:
#   test:
#     name: test
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16